### ISSUE TITLE
softDeletes does not seem to work as expected

### ISSUE THREAD

**Issue by ja-tomasz** [webNeat/lumen-generators#25]
it doesn't add 

```
use Illuminate\Database\Eloquent\SoftDeletes;
(...)
use SoftDeletes
```

...to the model. I tried php artisan wn:resource test tekst;string;; --add=timestamps;softDeletes and also the resources file

**Comment by webNeat** [comment]
Hello, Thanks for reporting this bug, will to fix it soon

**Comment by webNeat** [comment]
Fixed https://github.com/webNeat/lumen-generators/commit/8e57d36894488d27cf3b93aab460846fdec7ee21 :smile:

**Comment by ja-tomasz** [comment]
Great! Thanks!

**Comment by ja-tomasz** [comment]
this still does not work properly - the trait does not get found due to fully qualified class name being referenced from the App level:

> Fatal error: Trait 'App\Illuminate\Database\Eloquent\SoftDeletes' not found in ...

this works fine:

> use \Illuminate\Database\Eloquent\SoftDeletes;

**Comment by webNeat** [comment]
my bad, willing to fix this

**Comment by webNeat** [comment]
This is fixed
Commit: https://github.com/webNeat/lumen-generators/commit/5cf6f6ed9c55610a49d55cb9cba58a83a2e646dd
Release: https://github.com/webNeat/lumen-generators/releases/tag/1.3.3
